In [3]:
library(knitr)
library(dplyr)
library(readxl)

In [4]:
data <- read.csv("card.csv")
summary(data)

      Ã¯..              X1          X2              X3               X4
 1      :    1   50000  : 3365   1  :11888   2      :14030   0       :   54
 10     :    1   20000  : 1976   2  :18112   1      :10585   1       :13659
 100    :    1   30000  : 1610   SEX:    1   3      : 4917   2       :15964
 1000   :    1   80000  : 1567               5      :  280   3       :  323
 10000  :    1   200000 : 1528               4      :  123   MARRIAGE:    1
 10001  :    1   150000 : 1110               6      :   51
 (Other):29995   (Other):18845               (Other):   15
       X5              X6              X7              X8
 29     : 1605   0      :14737   0      :15730   0      :15764
 27     : 1477   -1     : 5686   -1     : 6050   -1     : 5938
 28     : 1409   1      : 3688   2      : 3927   -2     : 4085
 30     : 1395   -2     : 2759   -2     : 3782   2      : 3819
 26     : 1256   2      : 2667   3      :  326   3      :  240
 31     : 1217   3      :  322   4      :   99   4      :   76
 (Other):21642   (Other):  142   (Other):   87   (Other):   79
       X9             X10             X11             X12
 0      :16455   0      :16947   0      :16286   0      : 2008
 -1     : 5687   -1     : 5539   -1     : 5740   390    :  244
 -2     : 4348   -2     : 4546   -2     : 4895   780    :   76
 2      : 3159   2      : 2626   2      : 2766   326    :   72
 3      :  180   3      :  178   3      :  184   316    :   63
 4      :   69   4      :   84   4      :   49   2500   :   59
 (Other):  103   (Other):   81   (Other):   81   (Other):27479
      X13             X14             X15             X16
 0      : 2506   0      : 2870   0      : 3195   0      : 3506
 390    :  231   390    :  275   390    :  246   390    :  235
 326    :   75   780    :   74   780    :  101   780    :   94
 780    :   75   326    :   63   316    :   68   316    :   79
 316    :   72   316    :   62   326    :   62   326    :   62
 2500   :   51   396    :   48   396    :   44   150    :   58
 (Other):26991   (Other):26609   (Other):26285   (Other):25967
      X17             X18             X19             X20
 0      : 4020   0      : 5249   0      : 5396   0      : 5968
 390    :  207   2000   : 1363   2000   : 1290   2000   : 1285
 780    :   86   3000   :  891   3000   :  857   1000   : 1103
 150    :   78   5000   :  698   5000   :  717   3000   :  870
 316    :   77   1500   :  507   1000   :  594   5000   :  721
 326    :   56   4000   :  426   1500   :  521   1500   :  490
 (Other):25477   (Other):20867   (Other):20626   (Other):19564
      X21             X22             X23
 0      : 6408   0      : 6703   0      : 7173
 1000   : 1394   1000   : 1340   1000   : 1299
 2000   : 1214   2000   : 1323   2000   : 1295
 3000   :  887   3000   :  947   3000   :  914
 5000   :  810   5000   :  814   5000   :  808
 1500   :  441   1500   :  426   1500   :  439
 (Other):18847   (Other):18448   (Other):18073
                          Y
 0                         :23364
 1                         : 6636
 default payment next month:    1